#!/usr/bin/env python3
'''Phase 2 acceptance: v3 semantics, AnswerSet integrity, cache, failures,
cost, replay with zero network, authority boundary, adversarial cases.
Run: python3 collector/tests/test_jev.py (no network; post_fn mocked throughout,
except one live-shape check that never runs here)
'''
import json
import os
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
import jev  # noqa: E402

TMP = tempfile.mkdtemp()
jev.CACHE_DIR = os.path.join(TMP, "cache")
jev.SPEND_DIR = os.path.join(TMP, "spend")
jev.CALL_LOG = os.path.join(TMP, "calls.jsonl")
jev.KEY_PATH = os.path.join(TMP, "keys", "k.json")
jev.RETRY_DELAY_S = 0
N = [0]

# Explicit key bootstrap (runtime never self-generates; tests do it once).
JEV_SEED, JEV_PUB = jev.keypair()
FOREIGN_SEED = bytes.fromhex("2a" * 32)
FOREIGN_PUB = jev.ed_pubkey(FOREIGN_SEED)


def state(**kw):
    s = {"context_hash": "h", "symbol": "EURUSD", "stage": "G0_PAPER",
         "question_set_version": "v3", "snapshot_epoch": 1,
         "indicators": {"regime": "range"}, "portfolio": {"exposure_pct": 0},
         "event_window": {"phase": "none"}, "risk_flags": {}}
    s.update(kw)
    return s


def good_resp(cost=0.00001):
    return {"model": jev.REVISION, "provider": jev.PROVIDER,
            "answers": {
                "enter": {"type": "noul", "noul": 0.9},
                "edge_family": {"type": "choice", "choice": "momentum",
                                "probabilities": {"momentum": 0.8}},
                "conviction": {"type": "score", "score": "strong"},
                "latent_risk": {"type": "noul", "noul": 0.1}},
            "usage": {"cost": cost}}


def mkpost(resp=None, err=None, calls=None):
    def f(body, key):
        (calls if calls is not None else []).append(body)
        N[0] += 1
        return resp, err
    return f


def check(name, cond):
    assert cond, name
    print("ok " + name)


# 0. Ed25519 vectors generated by an independent implementation
# (cryptography lib, used once as oracle; never a runtime dep).
# Implementation must reproduce exactly: pub, sig(empty), sig(hello).
seed = bytes.fromhex("1f" * 32)
pub = jev.ed_pubkey(seed)
check("ed25519-vector-pub",
      pub.hex() == "43046bfe4092b3e94994eada15dcc20d8aaa07b658fd3954eb8e0efb8bdca5de")
sig = jev.ed_sign(seed, b"")
check("ed25519-vector-sig",
      sig.hex() == "8955d79a7fd195fce73f15739cd9a34f6ed93dc9693309c6ab81e08a1c32d2"
      "c6b4e8014b52ac42f97f0049e75f8c0c37607ed1865cfa3e1fba77ce80e0f98b01")
check("ed25519-vector-hello",
      jev.ed_sign(seed, b"hello").hex() == "de8f7589babbe2e693cdb74dc1d3e8c3e"
      "1549782b95d2b9deaff8802fbe81c0d4fc14c685223617a92d709bb4723581c00f10b63d9"
      "fa1f6cd35febe80275c60c")
check("ed25519-self-verify", jev.ed_verify(pub, b"hello", jev.ed_sign(seed, b"hello")))
check("ed25519-tamper-fails",
      not jev.ed_verify(pub, b"hello!", jev.ed_sign(seed, b"hello")))

# 1. exact v3 question order + shape, no extra semantics
qs = jev.build_questions()
check("four-questions-order",
      list(qs) == ["enter", "edge_family", "conviction", "latent_risk"])
check("question-types",
      [qs[k]["type"] for k in qs] == ["noul", "choice", "score", "noul"])
check("questions-have-instructions",
      all("instructions" in qs[k] and "criteria" in qs[k] for k in qs))

# 2. happy path: ANSWER + signed artifact, cache write
row, art = jev.decide(state(), now=1000.0, key="k", post_fn=mkpost(good_resp()))
check("answer-action", row["action"] == "ANSWER"
      and row["cost"]["usd"] > 0 and row["cached"] is False
      and set(row["cost"]) == {"stage", "cycle_id", "symbol", "node", "model",
                               "prompt_tokens", "completion_tokens", "usd",
                               "category"}
      and row["cost"]["category"] == "decision"
      and row["cost"]["node"] == "jev")
check("artifact-signed", jev.verify_answerset(art))
check("artifact-pins", art["payload"]["revision"] == jev.REVISION
      and art["payload"]["provider"] == jev.PROVIDER
      and art["payload"]["question_set_version"] == "v3")
check("no-size-fields", not any(k in row for k in
      ("size", "notional", "budget", "leverage", "order", "quantity")))

# 3. cache hit: identical state, zero new calls, cost 0
calls = []
row2, art2 = jev.decide(state(), now=1010.0, key="k",
                        post_fn=mkpost(good_resp(), calls=calls))
check("cache-hit", row2["action"] == "CACHED" and row2["cost"]["usd"] == 0.0
      and calls == [] and art2["response_hash"] == art["response_hash"])

# 4. cache invalidations: changed decision state, protected state, age
row3, _ = jev.decide(state(snapshot_epoch=2), now=1011.0, key="k",
                     post_fn=mkpost(good_resp(), calls=calls))
check("decision-change-reissues", row3["action"] == "ANSWER" and len(calls) == 1)
row4, _ = jev.decide(state(stage="G1_TINY"), now=1012.0, key="k",
                     post_fn=mkpost(good_resp(), calls=calls))
check("protected-change-reissues", row4["action"] == "ANSWER" and len(calls) == 2)
row5, _ = jev.decide(state(), now=5000.0, key="k",
                     post_fn=mkpost(good_resp(), calls=calls))
check("stale-answer-reissues", row5["action"] == "ANSWER" and len(calls) == 3)

# 5. failures -> HOLD, never fabricate. Ambiguous transport (timeout with
# no response: the provider may have billed us) never retries and never
# refunds: the reservation stands, the governor trips, a human reconciles.
calls5 = []
jev.SPEND_DIR = os.path.join(TMP, "spendAmb")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
row, art = jev.decide(state(symbol="X"), now=2000.0, key="k",
                      post_fn=mkpost(err="provider-error:Timeout", calls=calls5))
check("timeout-ambiguous-hold",
      row["action"] == "HOLD" and row["reason"] == "ambiguous-transport"
      and len(calls5) == 1 and art is None)
_s, _p = jev.spend_today(2000.0)
check("ambiguous-no-refund",
      _s["usd"] == jev.MAX_AUTHORIZED_CALL_USD
      and _s.get("unknown_charges") == 1 and _s["calls"] == 1)
row_b, _ = jev.decide(state(symbol="X2"), now=2001.0, key="k",
                      post_fn=mkpost(good_resp()))
check("ambiguous-trips-governor", row_b["reason"] == "spend-unknown")
jev.SPEND_DIR = os.path.join(TMP, "spend")
# Answered failures (HTTP 5xx DID arrive) still retry once, then HOLD.
calls5b = []
row, art = jev.decide(state(symbol="X5"), now=2002.0, key="k",
                      post_fn=mkpost(err="provider-http-500", calls=calls5b))
check("http500-retry-once-hold",
      row["action"] == "HOLD" and row["reason"].startswith("jev_error")
      and len(calls5b) == 2 and art is None)

# 6. adversarial responses
bad_cases = [
    ("malformed-json", "not-a-dict"),
    ("missing-fields", {"model": jev.REVISION}),
    ("wrong-types", {"model": jev.REVISION,
                     "answers": {"enter": {"type": "noul", "noul": "high"}}}),
    ("answers-keys", None),  # filled below
    ("wrong-revision", dict(good_resp(), model="typesafe/jev-9.99")),
    ("noul-range", None),
]
r = json.loads(json.dumps(good_resp()))
r["answers"]["enter"]["noul"] = 1.5
bad_cases[5] = ("noul-range", r)
r = json.loads(json.dumps(good_resp()))
r["answers"]["mystery"] = {"type": "noul", "noul": 0.5}
bad_cases[3] = ("answers-keys", r)
for name, resp in bad_cases:
    a, why = jev.validate_response(resp)
    check(name, a is None and isinstance(why, str))

# 7. tampered artifact: altered answers / state hash fail verify
row, art = jev.decide(state(symbol="Y"), now=3000.0, key="k",
                      post_fn=mkpost(good_resp()))
art2 = json.loads(json.dumps(art))
art2["payload"]["answers"]["enter"]["noul"] = 0.01
check("altered-response-fails", not jev.verify_answerset(art2))
art3 = json.loads(json.dumps(art))
art3["payload"]["state_hash"] = "0" * 64
check("altered-statehash-fails", not jev.verify_answerset(art3))
art4 = json.loads(json.dumps(art))
art4["signature"] = "00" * 64
check("tampered-sig-fails", not jev.verify_answerset(art4))

# 8. replay: zero network, identical input
p = os.path.join(TMP, "art.json")
json.dump(art, open(p, "w"))
def boom(body, key):
    raise AssertionError("replay must not call provider")
out = jev.replay(p)
check("replay-answers", out["action"] == "ANSWER"
      and out["answers"]["enter"]["noul"] == 0.9 and out["replayed"] is True)
jev_post_orig = jev.post
jev.post = boom
try:
    out = jev.replay(p)
    check("replay-zero-network", out["action"] == "ANSWER")
finally:
    jev.post = jev_post_orig
seed_x, pub_x = FOREIGN_SEED, FOREIGN_PUB
foreign = dict(art["payload"])
foreign["revision"] = "typesafe/jev-9.99"
msg_x = jev.canon(foreign).encode()
bad_art = {"payload": foreign}
bad_art["response_hash"] = jev.sha256_hex(jev.canon(foreign))
bad_art["signature"] = jev.ed_sign(seed_x, msg_x).hex()
bad_art["pubkey"] = pub_x.hex()
pb = os.path.join(TMP, "bad.json")
json.dump(bad_art, open(pb, "w"))
check("replay-foreign-key-hold",
      jev.replay(pb)["reason"] == "signature-failure")
# wrong revision signed by the CONFIGURED key still fails at pins
cfg_bad = json.loads(json.dumps(art["payload"]))
cfg_bad["revision"] = "typesafe/jev-9.99"
msg_c = jev.canon(cfg_bad).encode()
rb = {"payload": cfg_bad,
      "response_hash": jev.sha256_hex(jev.canon(cfg_bad)),
      "signature": jev.ed_sign(JEV_SEED, msg_c).hex(),
      "pubkey": JEV_PUB.hex()}
pc = os.path.join(TMP, "bad2.json")
json.dump(rb, open(pc, "w"))
check("replay-wrong-revision-hold",
      jev.replay(pc)["reason"] == "wrong-revision")

# 9. cost ceiling: pre-exhausted day blocks without calling
# Seed the DECISION-clock day (ledgers key on decide's now, not wall).
day = jev._day_of(4000.0)
jev.SPEND_DIR = os.path.join(TMP, "spend2")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
json.dump({"usd": 0.0, "calls": 5000, "prompt_tokens": 0,
           "completion_tokens": 0},
          open(os.path.join(jev.SPEND_DIR, day + ".json"), "w"))
calls9 = []
row, _ = jev.decide(state(symbol="Z"), now=4000.0, key="k",
                    post_fn=mkpost(good_resp(), calls=calls9))
check("call-ceiling-blocks",
      row["reason"] == "spend-call-ceiling" and calls9 == [])
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10. authority: max conviction + execution family pass through untouched;
#     adapter emits no budget/risk verdicts of its own
resp = good_resp()
resp["answers"]["conviction"]["score"] = "max"
resp["answers"]["edge_family"]["choice"] = "execution"
row, _ = jev.decide(state(symbol="W"), now=4100.0, key="k",
                    post_fn=mkpost(resp))
check("adapter-passthrough-only",
      row["action"] == "ANSWER"
      and row["answers"]["conviction"]["score"] == "max"
      and "2xR" not in json.dumps(row) and "budget" not in json.dumps(row))

# 11b. finite noul: bool/NaN/Inf rejected
import math as _math
for bad_v, name in [(True, "enter-true"), (False, "enter-false"),
                    (float("nan"), "enter-nan"), (float("inf"), "enter-inf")]:
    r = json.loads(json.dumps(good_resp()))
    r["answers"]["enter"]["noul"] = bad_v
    a, why = jev.validate_response(r)
    check(name, a is None)
for bad_v, name in [(True, "latent-true"), (float("nan"), "latent-nan")]:
    r = json.loads(json.dumps(good_resp()))
    r["answers"]["latent_risk"]["noul"] = bad_v
    a, why = jev.validate_response(r)
    check(name, a is None)

# 11c. provider identity enforced
r = json.loads(json.dumps(good_resp()))
r["provider"] = "SomeoneElse"
a, why = jev.validate_response(r)
check("wrong-provider", a is None and why == "wrong-provider")

# 11d. artifact schema: self-describing for C++
row, art = jev.decide(state(symbol="Q"), now=4300.0, key="k",
                      post_fn=mkpost(good_resp()))
pl = art["payload"]
check("artifact-schema",
      set(pl) == {"schema_version", "question_set_version", "model",
                  "revision", "provider", "symbol", "snapshot_epoch",
                  "state_hash", "decision_key", "created_at", "expires_at",
                  "answers"}
      and pl["symbol"] == "Q" and pl["expires_at"] > 4300.0)

# 11e. state binding explicit
check("bind-check-true", jev.bind_check(art, state(symbol="Q")) is True)
check("bind-check-changed-state",
      jev.bind_check(art, state(symbol="Q", snapshot_epoch=99)) is False)
check("bind-check-wrong-symbol",
      jev.bind_check(art, state(symbol="OTHER")) is False)

# 11f. failed attempts carry explicit unknown cost
row, _ = jev.decide(state(symbol="QF"), now=4400.0, key="k",
                    post_fn=mkpost(err="provider-http-500"))
check("unknown-cost-tagged",
      row["action"] == "HOLD" and row["cost"]["usd"] == "unknown"
      and row["cost"]["category"] == "decision")

# 11g. stage 30d USD cap governs (doc 10 units)
jev.SPEND_DIR = os.path.join(TMP, "spend3")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
json.dump({"usd": 150.0, "calls": 5, "prompt_tokens": 0,
           "completion_tokens": 0},
          open(os.path.join(jev.SPEND_DIR, jev._day_of(4500.0)
                             + ".json"), "w"))
calls_g = []
row, _ = jev.decide(state(symbol="QG"), now=4500.0, key="k",
                    post_fn=mkpost(good_resp(), calls=calls_g))
check("stage-cap-blocks",
      row["reason"] == "spend-stage-cap" and calls_g == [])
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10b. every provider attempt counts EXACTLY once; ambiguous transport
# never retries (one attempt, one reservation, governor tripped).
jev.SPEND_DIR = os.path.join(TMP, "spend4")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
calls_f = []
row, _ = jev.decide(state(symbol="F"), now=4600.0, key="k",
                    post_fn=mkpost(err="provider-error:Timeout", calls=calls_f))
check("attempts-counted",
      row["reason"] == "ambiguous-transport" and len(calls_f) == 1
      and jev.spend_today(4600.0)[0]["calls"] == 1)
# answered-transient retries cost one reservation per attempt, refunded
# per attempt: two attempts, two calls counted, money net zero.
# (Fresh ledger: the ambiguous failure above tripped this dir's governor.)
jev.SPEND_DIR = os.path.join(TMP, "spend4r")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
calls_r = []
row, _ = jev.decide(state(symbol="F5"), now=4600.5, key="k",
                    post_fn=mkpost(err="provider-http-503", calls=calls_r))
_s4, _ = jev.spend_today(4600.5)
check("retry-counted-refunded",
      row["reason"].startswith("jev_error") and len(calls_r) == 2
      and _s4["calls"] == 2 and _s4["usd"] == 0.0)
jev.SPEND_DIR = os.path.join(TMP, "spend")
jev.SPEND_DIR = os.path.join(TMP, "spend")
# non-transient errors never retry: one attempt, one call
jev.SPEND_DIR = os.path.join(TMP, "spend4b")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
calls_nr = []
row, _ = jev.decide(state(symbol="F2"), now=4601.0, key="k",
                    post_fn=mkpost(err="provider-http-401", calls=calls_nr))
check("no-retry-401",
      row["action"] == "HOLD" and len(calls_nr) == 1
      and row["reason"] == "jev_error:provider-http-401")
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10c. rolling 30d ignores stale files
jev.SPEND_DIR = os.path.join(TMP, "spend5")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
old_day = (__import__("datetime").datetime.now(
    __import__("datetime").timezone.utc)
    - __import__("datetime").timedelta(days=40)).strftime("%Y-%m-%d")
json.dump({"usd": 999.0, "calls": 1},
          open(os.path.join(jev.SPEND_DIR, old_day + ".json"), "w"))
check("rolling-window-true", jev.spend_30d()[0] == 0.0)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10d. unknown stage fails closed before any provider call
calls_s = []
bad_st = state(symbol="S")
bad_st["stage"] = "G9_MOON"
row, _ = jev.decide(bad_st, now=4700.0, key="k",
                    post_fn=mkpost(good_resp(), calls=calls_s))
check("invalid-stage",
      row["reason"] == "invalid-stage" and calls_s == [])

# 11. bad state input holds deterministically
row, _ = jev.decide({"symbol": "X"}, now=4200.0, key="k",
                    post_fn=mkpost(good_resp()))
check("bad-state-hold", row["action"] == "HOLD")
row, _ = jev.decide("garbage", now=4200.0, key="k",
                    post_fn=mkpost(good_resp()))
check("nonobject-state-hold", row["action"] == "HOLD")

# 12. B2 exact attempt accounting: success/failure/retries count once each
jev.SPEND_DIR = os.path.join(TMP, "spendX")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
row, _ = jev.decide(state(symbol="X1"), now=5000.0, key="k",
                     post_fn=mkpost(good_resp()))
check("one-success-one-call",
      row["action"] == "ANSWER" and jev.spend_today(5000.0)[0]["calls"] == 1)
row, _ = jev.decide(state(symbol="X2"), now=5001.0, key="k",
                     post_fn=mkpost(err="provider-http-400"))
check("one-failure-one-call",
      row["action"] == "HOLD" and jev.spend_today(5001.0)[0]["calls"] == 2)
row, _ = jev.decide(state(symbol="X3"), now=5002.0, key="k",
                     post_fn=mkpost(good_resp()))
check("success-after-failure",
      row["action"] == "ANSWER" and jev.spend_today(5002.0)[0]["calls"] == 3)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 13. B3 corrupt ledger fails closed (never $0), no provider call
jev.SPEND_DIR = os.path.join(TMP, "spendBad")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
for name, blob in [("corrupt-json", "{nope"),
                    ("array-shape", "[]"),
                    ("negative-usd", '{"usd": -5, "calls": 0, '
                     '"prompt_tokens": 0, "completion_tokens": 0}'),
                    ("string-calls", '{"usd": 0, "calls": "3", '
                     '"prompt_tokens": 0, "completion_tokens": 0}')]:
    p = os.path.join(jev.SPEND_DIR, jev._day_of(5100.0) + ".json")
    open(p, "w").write(blob)
    calls_b = []
    row, _ = jev.decide(state(symbol="XB"), now=5100.0, key="k",
                         post_fn=mkpost(good_resp(), calls=calls_b))
    check("spend-" + name,
          row["reason"] == "spend-unknown" and calls_b == [])
    os.remove(p)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 14. B5 artifact pubkey is informational: mutation changes nothing
row, art = jev.decide(state(symbol="XK"), now=5200.0, key="k",
                       post_fn=mkpost(good_resp()))
mut = json.loads(json.dumps(art))
mut["pubkey"] = FOREIGN_PUB.hex()
check("pubkey-mutation-irrelevant", jev.verify_answerset(mut) is True)
check("verify-needs-configured-key", jev.verify_answerset(art) is True)

# 15. B8 malformed usage poisons the governor AND blocks the answer:
# an unknowable bill is unbounded by the reservation, so no ANSWER may
# enter the decision path (unknown-cost HOLD), and the governor holds after.
for bad_usage, name in [({"cost": -10.0}, "neg-cost"),
                         ({"cost": float("nan")}, "nan-cost"),
                         ({"cost": 1e18}, "huge-cost"),
                         ({"cost": 0.01, "prompt_tokens": -1}, "neg-tokens"),
                         ({"cost": 0.01, "prompt_tokens": True}, "bool-tokens")]:
    jev.SPEND_DIR = os.path.join(TMP, "spendU-" + name)
    os.makedirs(jev.SPEND_DIR, exist_ok=True)
    r = good_resp()
    r["usage"] = bad_usage
    row, art_u = jev.decide(state(symbol="XU" + name), now=5300.0, key="k",
                         post_fn=mkpost(r))
    check("usage-" + name,
          row["action"] == "HOLD" and row["reason"] == "unknown-cost"
          and row["cost"]["usd"] == "unknown" and art_u is None)
jev.SPEND_DIR = os.path.join(TMP, "spendU-gov")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
r = good_resp()
r["usage"] = {"cost": -1.0}
row, _ = jev.decide(state(symbol="XUg"), now=5300.0, key="k",
                     post_fn=mkpost(r))
check("usage-poisoned", row["action"] == "HOLD"
      and row["reason"] == "unknown-cost")
row, _ = jev.decide(state(symbol="XU2"), now=5301.0, key="k",
                     post_fn=mkpost(good_resp()))
check("governor-unknown-holds", row["reason"] == "spend-unknown")
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 16. B10 missing key material HOLDs, never rotates
old_key = jev.KEY_PATH
jev.KEY_PATH = os.path.join(TMP, "nokeys", "k.json")
row, _ = jev.decide(state(symbol="XN"), now=5400.0, key="k",
                     post_fn=mkpost(good_resp()))
check("missing-key-holds",
      row["reason"].startswith("signing-key-unavailable"))
check("no-silent-keygen", not os.path.exists(jev.KEY_PATH))
jev.KEY_PATH = old_key

# 17. B11 strict state admission
for extra, name in [({"indicators": [1]}, "indicators-list"),
                    ({"snapshot_epoch": True}, "epoch-bool"),
                    ({"snapshot_epoch": -1}, "epoch-neg"),
                    ({"spread_bps": "wide"}, "spread-str"),
                    ({"features": [{"feature_id": 7}]}, "feature-id-int"),
                    ({"context_hash": ""}, "empty-hash")]:
    row, _ = jev.decide(state(symbol="XS", **extra), now=5500.0, key="k",
                         post_fn=mkpost(good_resp()))
    check("admit-" + name, row["action"] == "HOLD")

# 18. B7 strict nested response mirroring C++
r = good_resp()
r["answers"]["edge_family"]["probabilities"] = {"vibes": 0.5}
check("prob-key-rejected", jev.validate_response(r)[0] is None)
r = good_resp()
r["answers"]["edge_family"]["confidence"] = True
check("conf-bool-rejected", jev.validate_response(r)[0] is None)
r = good_resp()
r["answers"]["enter"]["extra"] = 1
check("enter-extra-rejected", jev.validate_response(r)[0] is None)
r = good_resp()
r["answers"]["edge_family"]["probabilities"] = {"momentum": 2.0}
check("prob-range-rejected", jev.validate_response(r)[0] is None)

# 19. B6 future-dated cache is a miss, not a hit
row, art = jev.decide(state(symbol="XC"), now=5600.0, key="k",
                       post_fn=mkpost(good_resp()))
import glob as _glob
for _cp in _glob.glob(os.path.join(jev.CACHE_DIR, "*.json")):
    _c = json.load(open(_cp))
    _c["at"] = 9999999999.0
    json.dump(_c, open(_cp, "w"))
calls_c = []
row, _ = jev.decide(state(symbol="XC"), now=5601.0, key="k",
                     post_fn=mkpost(good_resp(), calls=calls_c))
check("future-cache-miss",
      row["action"] == "ANSWER" and len(calls_c) == 1)

# 20. spend_charge() failure FAILS CLOSED: no sign, no cache, no ANSWER
jev.SPEND_DIR = os.path.join(TMP, "spendCharge")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
_real_charge = jev.spend_charge
_real_charge_now = jev._charge_now
_real_settle = jev._settle_now
jev.spend_charge = lambda *a, **k: None
jev._charge_now = lambda *a, **k: None
jev._settle_now = lambda *a, **k: (None, "unknown")
calls_z = []
row, art = jev.decide(state(symbol="XZ"), now=5700.0, key="k",
                      post_fn=mkpost(good_resp(), calls=calls_z))
jev.spend_charge = _real_charge
jev._charge_now = _real_charge_now
jev._settle_now = _real_settle
check("charge-fail-hold",
      row["action"] == "HOLD" and row["reason"] == "spend-unknown"
      and art is None)
check("charge-fail-no-cache",
      jev.cache_get(state(symbol="XZ"), 5701.0) is None)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 21. malformed spend filenames poison the 30d governor (never vanish)
jev.SPEND_DIR = os.path.join(TMP, "spendF")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
open(os.path.join(jev.SPEND_DIR, "garbage.json"), "w").write("{}")
check("spend-malformed-name", jev.spend_30d() == (0.0, True))
os.remove(os.path.join(jev.SPEND_DIR, "garbage.json"))
open(os.path.join(jev.SPEND_DIR, "notes.txt"), "w").write("x")
check("spend-stray-file", jev.spend_30d()[1] is True)
os.remove(os.path.join(jev.SPEND_DIR, "notes.txt"))
check("spend-clean-zero", jev.spend_30d() == (0.0, False))
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 22. confidence: absent = unknown (accepted); explicit null REJECTED
# (C++ checkconf requires a number); finite number accepted
r = good_resp()
r["answers"]["edge_family"]["confidence"] = None
check("conf-null-family", jev.validate_response(r)[0] is None)
r = good_resp()
r["answers"]["conviction"]["confidence"] = None
check("conf-null-conviction", jev.validate_response(r)[0] is None)
r = good_resp()
r["answers"]["edge_family"]["confidence"] = 0.7
r["answers"]["conviction"]["confidence"] = 0.2
a, why = jev.validate_response(r)
check("conf-numeric",
      a is not None and a["edge_family"]["confidence"] == 0.7
      and a["conviction"]["confidence"] == 0.2)

# 23. recursive state admission: nested NaN/Infinity/non-JSON rejected
import math as _m2
for extra, name in [({"indicators": {"deep": {"v": _m2.nan}}}, "nested-nan"),
                    ({"indicators": {"deep": [_m2.inf]}}, "nested-inf"),
                    ({"event_window": {"x": {"y": 1}}}, "nested-ok-shape")]:
    row, _ = jev.decide(state(symbol="XN2", **extra), now=5800.0, key="k",
                        post_fn=mkpost(good_resp()))
    if name == "nested-ok-shape":
        check(name, row["action"] == "ANSWER")
    else:
        check(name, row["action"] == "HOLD"
              and row["reason"] == "state-nonfinite")

# 24. OS-native lock: acquire/release/reacquire; a live holder in ANOTHER
# process blocks acquisition (locks are process-owned: same-process
# threads would not prove exclusion, so the holder is a subprocess).
lockp = os.path.join(TMP, "test.lock")
with jev._FileLock(lockp):
    check("lock-held", os.path.exists(lockp))
with jev._FileLock(lockp, timeout=1.0):
    check("lock-reacquire", True)
import subprocess as _sp
_holder_code = (
    "import sys, time; sys.path.insert(0, %r); "
    "from jev import _FileLock; "
    "f = _FileLock(%r); f.__enter__(); time.sleep(8)" % (HERE, lockp))
proc = _sp.Popen([sys.executable, "-c", _holder_code])
try:
    time.sleep(1.5)  # let the holder acquire
    try:
        with jev._FileLock(lockp, timeout=1.0):
            blocked = False
    except TimeoutError:
        blocked = True
    check("lock-contention", blocked)
finally:
    proc.terminate()
    proc.wait()

# 25. log rotation is atomic: tail stays valid JSONL
jev.CALL_LOG_MAX_BYTES = 200
for i in range(50):
    jev.log_row({"i": i, "pad": "x" * 100})
with open(jev.CALL_LOG, "rb") as _lf:
    _lines = _lf.read().split(b"\n")
nonempty = [ln for ln in _lines if ln.strip()]
check("log-rotation-valid",
      len(nonempty) > 0
      and all(json.loads(ln)["i"] >= 0 for ln in nonempty))
jev.CALL_LOG_MAX_BYTES = 8 * 1024 * 1024

# 26. malformed provider response + failed charge -> spend-unknown
# (accounting failure after an attempt, not the response's own HOLD)
jev.SPEND_DIR = os.path.join(TMP, "spendMC")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
jev._settle_now = lambda *a, **k: (None, "unknown")
_bad = json.loads(json.dumps(good_resp()))
_bad["answers"]["enter"]["noul"] = "high"
row, art = jev.decide(state(symbol="XMC"), now=5900.0, key="k",
                      post_fn=mkpost(_bad))
jev._settle_now = _real_settle
check("malformed-charge-fail",
      row["action"] == "HOLD" and row["reason"] == "spend-unknown"
      and art is None)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 27. cache wrapper hardening: NaN at, extra keys, incoherent expiry
row, art = jev.decide(state(symbol="XW"), now=6000.0, key="k",
                      post_fn=mkpost(good_resp()))
import glob as _glob2
_cp = _glob2.glob(os.path.join(jev.CACHE_DIR, "*.json"))
assert _cp, "cache file expected"


def _mutate(fn):
    for _p in _cp:
        with open(_p, encoding="utf-8") as _fh:
            _c = json.load(_fh)
        fn(_c)
        with open(_p, "w", encoding="utf-8") as _fh:
            json.dump(_c, _fh)


def _fresh_decide():
    _calls = []
    _row, _ = jev.decide(state(symbol="XW"), now=6001.0, key="k",
                         post_fn=mkpost(good_resp(), calls=_calls))
    return _row, _calls

_mutate(lambda c: c.update(at=float("nan")))
_r, _cl = _fresh_decide()
check("cache-nan-at", _r["action"] == "ANSWER" and len(_cl) == 1)
_mutate(lambda c: c.update(at=6000.5, smuggled=1))
_r, _cl = _fresh_decide()
check("cache-extra-key", _r["action"] == "ANSWER" and len(_cl) == 1)
_mutate(lambda c: c.update(at=6000.5))
_mutate(lambda c: c["artifact"]["payload"].update(expires_at=999999.0))
_r, _cl = _fresh_decide()
check("cache-expiry-incoherent", _r["action"] == "ANSWER"
      and len(_cl) == 1)
_mutate(lambda c: c["artifact"].pop("pubkey"))
_r, _cl = _fresh_decide()
check("cache-artifact-keys", _r["action"] == "ANSWER" and len(_cl) == 1)

# 28. temp-file pattern is exact: near-misses poison the governor
jev.SPEND_DIR = os.path.join(TMP, "spendT")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
for _fn in ["fraud.tmp-hidden.json", "foo.tmp-contains-real-spend",
             "2026-09-20.json.tmp-abc", "2026-09-20.json.tmp-"]:
    open(os.path.join(jev.SPEND_DIR, _fn), "w").write("{}")
    check("spend-tmp-" + _fn[:12], jev.spend_30d()[1] is True)
    os.remove(os.path.join(jev.SPEND_DIR, _fn))
_legit = (jev.datetime.now(jev.timezone.utc).strftime("%Y-%m-%d")
          + ".json.tmp-12345")
open(os.path.join(jev.SPEND_DIR, _legit), "w").write("{}")
check("spend-tmp-legit", jev.spend_30d() == (0.0, False))
os.remove(os.path.join(jev.SPEND_DIR, _legit))
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 29. two-process money gate: concurrent racers cannot jointly cross the
# stage cap. Seed $148.00: the first $0.01 call reserves $2.00 (peak
# exactly $150.00, never above), settles to $148.01; the second then
# needs $150.01 of headroom it no longer has -> HOLD spend-stage-cap.
# (Pre-fix, both observed headroom and jointly overshot; the reservation
# makes the cap pre-call. Peak ledger is bounded by construction:
# reserve authorizes only total+R<=cap, settle only decreases it.)
import subprocess as _sp2
_cap_dir = os.path.join(TMP, "spendCap")
os.makedirs(_cap_dir, exist_ok=True)
_day = jev.datetime.now(jev.timezone.utc).strftime("%Y-%m-%d")
with open(os.path.join(_cap_dir, _day + ".json"), "w",
          encoding="utf-8") as _fh:
    json.dump({"usd": 148.00, "calls": 0, "prompt_tokens": 0,
               "completion_tokens": 0, "unknown_charges": 0}, _fh)
_child_lines = [
    "import sys, json, time",
    "sys.path.insert(0, %r)" % HERE,
    "import jev",
    "jev.SPEND_DIR = %r" % _cap_dir,
    "jev.CACHE_DIR = %r" % os.path.join(TMP, "cacheCap"),
    "jev.CALL_LOG = %r" % os.path.join(TMP, "callsCap.jsonl"),
    "jev.KEY_PATH = %r" % jev.KEY_PATH,
    "jev.RETRY_DELAY_S = 0",
    "resp = {'model': jev.REVISION, 'provider': jev.PROVIDER, ",
    "'answers': {'enter': {'type': 'noul', 'noul': 0.9}, ",
    "'edge_family': {'type': 'choice', 'choice': 'momentum', ",
    "'probabilities': {'momentum': 0.8}}, ",
    "'conviction': {'type': 'score', 'score': 'strong'}, ",
    "'latent_risk': {'type': 'noul', 'noul': 0.1}}, ",
    "'usage': {'cost': 0.01}}",
    "def post_fn(body, key):",
    "    time.sleep(0.5); return (resp, None)",
    "st = {'context_hash': 'h', 'symbol': sys.argv[1], ",
    "'stage': 'G0_PAPER', 'question_set_version': 'v3', ",
    "'snapshot_epoch': 1}",
    "row, _ = jev.decide(st, now=time.time(), key='k', post_fn=post_fn)",
    "print(json.dumps({'action': row['action'], ",
    "'reason': row.get('reason')}))",
]
_child = "\n".join(_child_lines)
_procs = [_sp2.Popen([sys.executable, "-c", _child, sym],
                      stdout=_sp2.PIPE, text=True)
          for sym in ("CAPA", "CAPB")]
_outs = [json.loads(p.communicate()[0]) for p in _procs]
_saved_spend = jev.SPEND_DIR
jev.SPEND_DIR = _cap_dir
_cap_total, _cap_unk = jev.spend_30d()
jev.SPEND_DIR = _saved_spend
_actions = sorted(o["action"] for o in _outs)
check("cap-race-serialized",
      _actions == ["ANSWER", "HOLD"]
      and _cap_total <= 150.0 and _cap_unk is False
      and sum(1 for o in _outs
              if o.get("reason") == "spend-stage-cap") == 1)

# 30. expired signed artifact is never served, even with a fresh wrapper.
jev.SPEND_DIR = os.path.join(TMP, "spendExp")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
row, art = jev.decide(state(symbol="XE"), now=7000.0, key="k",
                      post_fn=mkpost(good_resp()))
check("expiry-setup", row["action"] == "ANSWER")
import glob as _glob3
_cp3 = _glob3.glob(os.path.join(jev.CACHE_DIR, "*.json"))
assert _cp3, "cache file expected"
for _p in _cp3:
    with open(_p, encoding="utf-8") as _fh:
        _c = json.load(_fh)
    # Age the SIGNED artifact 120 s (expired) but keep the wrapper fresh.
    _created = 7000.0 - 120.0
    _iso = jev.datetime.fromtimestamp(_created, jev.timezone.utc).isoformat()
    _c["artifact"]["payload"]["created_at"] = _iso
    _c["artifact"]["payload"]["expires_at"] = _created + 60.0
    _c["artifact"]["response_hash"] = jev.sha256_hex(
        jev.canon(_c["artifact"]["payload"]))
    _msg = jev.canon(_c["artifact"]["payload"]).encode()
    _c["artifact"]["signature"] = jev.ed_sign(JEV_SEED, _msg).hex()
    _c["at"] = 6999.0  # wrapper fresh (1 s old at now=7000)
    with open(_p, "w", encoding="utf-8") as _fh:
        json.dump(_c, _fh)
_calls_e = []
row_e, _ = jev.decide(state(symbol="XE"), now=7000.0, key="k",
                      post_fn=mkpost(good_resp(), calls=_calls_e))
check("expired-artifact-miss",
      row_e["action"] == "ANSWER" and len(_calls_e) == 1)
# Future-dated creation beyond skew is also a miss.
for _p in _glob3.glob(os.path.join(jev.CACHE_DIR, "*.json")):
    with open(_p, encoding="utf-8") as _fh:
        _c = json.load(_fh)
    if _c["artifact"]["payload"].get("symbol") != "XE":
        continue
    _created = 7000.0 + 3600.0
    _iso = jev.datetime.fromtimestamp(_created, jev.timezone.utc).isoformat()
    _c["artifact"]["payload"]["created_at"] = _iso
    _c["artifact"]["payload"]["expires_at"] = _created + 60.0
    _c["artifact"]["response_hash"] = jev.sha256_hex(
        jev.canon(_c["artifact"]["payload"]))
    _msg = jev.canon(_c["artifact"]["payload"]).encode()
    _c["artifact"]["signature"] = jev.ed_sign(JEV_SEED, _msg).hex()
    _c["at"] = 7000.0
    with open(_p, "w", encoding="utf-8") as _fh:
        json.dump(_c, _fh)
_calls_f = []
row_f, _ = jev.decide(state(symbol="XE"), now=7000.0, key="k",
                      post_fn=mkpost(good_resp(), calls=_calls_f))
check("future-created-miss",
      row_f["action"] == "ANSWER" and len(_calls_f) == 1)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 31. single-call overshoot is impossible: $149.99 + $2.00 reservation
# does not fit a $150 cap, so the call is refused BEFORE sending.
jev.SPEND_DIR = os.path.join(TMP, "spendOver")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
with open(os.path.join(jev.SPEND_DIR, jev._day_of(7100.0) + ".json"),
          "w", encoding="utf-8") as _fh:
    json.dump({"usd": 149.99, "calls": 0, "prompt_tokens": 0,
               "completion_tokens": 0}, _fh)
_calls_o = []
row_o, _ = jev.decide(state(symbol="XO"), now=7100.0, key="k",
                      post_fn=mkpost(good_resp(cost=0.01), calls=_calls_o))
check("overshoot-refused",
      row_o["reason"] == "spend-stage-cap" and _calls_o == []
      and jev.spend_30d(7100.0) == (149.99, False))
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 32. decision-clock determinism: same now -> identical HOLD rows, and
# the ledger day-file is the decision day, never wall-clock day.
jev.SPEND_DIR = os.path.join(TMP, "spendClk")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
_clk_calls = []
h1, _ = jev.decide(state(symbol="XC"), now=7200.0, key="",
                   post_fn=mkpost(good_resp(), calls=_clk_calls))
h2, _ = jev.decide(state(symbol="XC"), now=7200.0, key="",
                   post_fn=mkpost(good_resp(), calls=_clk_calls))
check("hold-clock-deterministic",
      h1["action"] == "HOLD" and h1["at"] == h2["at"]
      and h1["at"] == jev.datetime.fromtimestamp(
          7200.0, jev.timezone.utc).isoformat()
      and _clk_calls == []
      and jev._day_of(7200.0) == "1970-01-01")
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 33. single-flight: two processes racing the same decision_key buy ONE
# provider call. Both miss the empty cache; the loser rechecks inside the
# lock and serves the winner's artifact instead of calling again.
import subprocess as _sp3
_sf_dir = os.path.join(TMP, "spendSF")
os.makedirs(_sf_dir, exist_ok=True)
_sf_cache = os.path.join(TMP, "cacheSF")
_sf_count = os.path.join(TMP, "callsSF.txt")
open(_sf_count, "w").write("")
_sf_lines = [
    "import sys, json, time",
    "sys.path.insert(0, %r)" % HERE,
    "import jev",
    "jev.SPEND_DIR = %r" % _sf_dir,
    "jev.CACHE_DIR = %r" % _sf_cache,
    "jev.CALL_LOG = %r" % os.path.join(TMP, "callsSF.jsonl"),
    "jev.KEY_PATH = %r" % jev.KEY_PATH,
    "jev.RETRY_DELAY_S = 0",
    "resp = {'model': jev.REVISION, 'provider': jev.PROVIDER, ",
    "'answers': {'enter': {'type': 'noul', 'noul': 0.9}, ",
    "'edge_family': {'type': 'choice', 'choice': 'momentum', ",
    "'probabilities': {'momentum': 0.8}}, ",
    "'conviction': {'type': 'score', 'score': 'strong'}, ",
    "'latent_risk': {'type': 'noul', 'noul': 0.1}}, ",
    "'usage': {'cost': 0.01}}",
    "def post_fn(body, key):",
    "    time.sleep(1.0)",
    "    open(%r, 'a').write('call\\n')" % _sf_count,
    "    return (resp, None)",
    "st = {'context_hash': 'sf', 'symbol': 'SF', ",
    "'stage': 'G0_PAPER', 'question_set_version': 'v3', ",
    "'snapshot_epoch': 1}",
    "row, _ = jev.decide(st, now=time.time(), key='k', post_fn=post_fn)",
    "print(json.dumps({'action': row['action']}))",
]
_sf_child = "\n".join(_sf_lines)
_sf_procs = [_sp3.Popen([sys.executable, "-c", _sf_child],
                        stdout=_sp3.PIPE, text=True) for _ in range(2)]
_sf_outs = sorted(json.loads(p.communicate()[0])["action"]
                  for p in _sf_procs)
_sf_calls = open(_sf_count).read().count("call")
check("single-flight",
      _sf_outs == ["ANSWER", "CACHED"] and _sf_calls == 1)

# 34. replay enforces the full artifact contract (never KeyError).
_p, _a = jev.decide(state(symbol="XR"), now=7300.0, key="k",
                    post_fn=mkpost(good_resp()))
_rp = os.path.join(TMP, "replay_ok.json")
json.dump(_a, open(_rp, "w"))
check("replay-ok", jev.replay(_rp)["action"] == "ANSWER")
_mut = json.loads(json.dumps(_a))
del _mut["payload"]["state_hash"]  # signed-but-malformed artifact
_mp = os.path.join(TMP, "replay_nosh.json")
json.dump(_mut, open(_mp, "w"))
_out = jev.replay(_mp)
check("replay-malformed-hold",
      _out["action"] == "HOLD" and _out["reason"] == "replay-shape")
_mut2 = json.loads(json.dumps(_a))
_mut2["payload"]["expires_at"] = 1.0  # incoherent lifetime
_mp2 = os.path.join(TMP, "replay_incoh.json")
json.dump(_mut2, open(_mp2, "w"))
check("replay-incoherent-hold",
      jev.replay(_mp2)["action"] == "HOLD")

# 35. paid-but-uncached degrades loudly, never crashes or double-spends
# silently: cache_put failure -> HOLD evidence-persist-failed.
_real_cache_put = jev.cache_put
jev.cache_put = lambda *a, **k: (_ for _ in ()).throw(OSError("disk full"))
row, art = jev.decide(state(symbol="XP"), now=7400.0, key="k",
                      post_fn=mkpost(good_resp()))
jev.cache_put = _real_cache_put
check("persist-failure-hold",
      row["action"] == "HOLD"
      and row["reason"].startswith("evidence-persist-failed")
      and art is None)
check("log-contained", jev.log_row({"x": 1}) is True)

# 36. future-dated spend ledger is corruption evidence, not ignorable.
jev.SPEND_DIR = os.path.join(TMP, "spendFuture")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
_future_day = (jev.datetime.now(jev.timezone.utc)
               + __import__("datetime").timedelta(days=400)).strftime("%Y-%m-%d")
with open(os.path.join(jev.SPEND_DIR, _future_day + ".json"),
          "w", encoding="utf-8") as _fh:
    json.dump({"usd": 0.0, "calls": 0, "prompt_tokens": 0,
               "completion_tokens": 0}, _fh)
check("spend-future-unknown", jev.spend_30d() == (0.0, True))
jev.SPEND_DIR = os.path.join(TMP, "spend")

print("ALL JEV CHECKS PASS")