#!/usr/bin/env python3
'''Phase 2 acceptance: v3 semantics, AnswerSet integrity, cache, failures,
cost, replay with zero network, authority boundary, adversarial cases.
Run: python3 collector/test_jev.py (no network; post_fn mocked throughout,
except one live-shape check that never runs here)
'''
import json
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import jev  # noqa: E402

TMP = tempfile.mkdtemp()
jev.CACHE_DIR = os.path.join(TMP, "cache")
jev.SPEND_DIR = os.path.join(TMP, "spend")
jev.CALL_LOG = os.path.join(TMP, "calls.jsonl")
jev.KEY_PATH = os.path.join(TMP, "keys", "k.json")
jev.RETRY_DELAY_S = 0
N = [0]


def state(**kw):
    s = {"context_hash": "h", "symbol": "EURUSD", "stage": "G0_PAPER",
         "question_set_version": "v3", "snapshot_epoch": 1,
         "indicators": {"regime": "range"}, "portfolio": {"exposure_pct": 0},
         "event_window": {"phase": "none"}, "risk_flags": {}}
    s.update(kw)
    return s


def good_resp(cost=0.00001):
    return {"model": jev.REVISION, "provider": jev.PROVIDER,
            "answers": {
                "enter": {"type": "noul", "noul": 0.9},
                "edge_family": {"type": "choice", "choice": "momentum",
                                "probabilities": {"momentum": 0.8}},
                "conviction": {"type": "score", "score": "strong"},
                "latent_risk": {"type": "noul", "noul": 0.1}},
            "usage": {"cost": cost}}


def mkpost(resp=None, err=None, calls=None):
    def f(body, key):
        (calls if calls is not None else []).append(body)
        N[0] += 1
        return resp, err
    return f


def check(name, cond):
    assert cond, name
    print("ok " + name)


# 0. Ed25519 vectors generated by an independent implementation
# (cryptography lib, used once as oracle; never a runtime dep).
# Implementation must reproduce exactly: pub, sig(empty), sig(hello).
seed = bytes.fromhex("1f" * 32)
pub = jev.ed_pubkey(seed)
check("ed25519-vector-pub",
      pub.hex() == "43046bfe4092b3e94994eada15dcc20d8aaa07b658fd3954eb8e0efb8bdca5de")
sig = jev.ed_sign(seed, b"")
check("ed25519-vector-sig",
      sig.hex() == "8955d79a7fd195fce73f15739cd9a34f6ed93dc9693309c6ab81e08a1c32d2"
      "c6b4e8014b52ac42f97f0049e75f8c0c37607ed1865cfa3e1fba77ce80e0f98b01")
check("ed25519-vector-hello",
      jev.ed_sign(seed, b"hello").hex() == "de8f7589babbe2e693cdb74dc1d3e8c3e"
      "1549782b95d2b9deaff8802fbe81c0d4fc14c685223617a92d709bb4723581c00f10b63d9"
      "fa1f6cd35febe80275c60c")
check("ed25519-self-verify", jev.ed_verify(pub, b"hello", jev.ed_sign(seed, b"hello")))
check("ed25519-tamper-fails",
      not jev.ed_verify(pub, b"hello!", jev.ed_sign(seed, b"hello")))

# 1. exact v3 question order + shape, no extra semantics
qs = jev.build_questions()
check("four-questions-order",
      list(qs) == ["enter", "edge_family", "conviction", "latent_risk"])
check("question-types",
      [qs[k]["type"] for k in qs] == ["noul", "choice", "score", "noul"])
check("questions-have-instructions",
      all("instructions" in qs[k] and "criteria" in qs[k] for k in qs))

# 2. happy path: ANSWER + signed artifact, cache write
row, art = jev.decide(state(), now=1000.0, key="k", post_fn=mkpost(good_resp()))
check("answer-action", row["action"] == "ANSWER"
      and row["cost"]["usd"] > 0 and row["cached"] is False
      and set(row["cost"]) == {"stage", "cycle_id", "symbol", "node", "model",
                               "prompt_tokens", "completion_tokens", "usd",
                               "category"}
      and row["cost"]["category"] == "decision"
      and row["cost"]["node"] == "jev")
check("artifact-signed", jev.verify_answerset(art))
check("artifact-pins", art["payload"]["revision"] == jev.REVISION
      and art["payload"]["provider"] == jev.PROVIDER
      and art["payload"]["question_set_version"] == "v3")
check("no-size-fields", not any(k in row for k in
      ("size", "notional", "budget", "leverage", "order", "quantity")))

# 3. cache hit: identical state, zero new calls, cost 0
calls = []
row2, art2 = jev.decide(state(), now=1010.0, key="k",
                        post_fn=mkpost(good_resp(), calls=calls))
check("cache-hit", row2["action"] == "CACHED" and row2["cost"]["usd"] == 0.0
      and calls == [] and art2["response_hash"] == art["response_hash"])

# 4. cache invalidations: changed decision state, protected state, age
row3, _ = jev.decide(state(snapshot_epoch=2), now=1011.0, key="k",
                     post_fn=mkpost(good_resp(), calls=calls))
check("decision-change-reissues", row3["action"] == "ANSWER" and len(calls) == 1)
row4, _ = jev.decide(state(stage="G1_TINY"), now=1012.0, key="k",
                     post_fn=mkpost(good_resp(), calls=calls))
check("protected-change-reissues", row4["action"] == "ANSWER" and len(calls) == 2)
row5, _ = jev.decide(state(), now=5000.0, key="k",
                     post_fn=mkpost(good_resp(), calls=calls))
check("stale-answer-reissues", row5["action"] == "ANSWER" and len(calls) == 3)

# 5. failures -> HOLD, retry once, never fabricate
calls5 = []
row, art = jev.decide(state(symbol="X"), now=2000.0, key="k",
                      post_fn=mkpost(err="provider-error:Timeout", calls=calls5))
check("timeout-retry-once-hold",
      row["action"] == "HOLD" and row["reason"].startswith("jev_error")
      and len(calls5) == 2 and art is None)

# 6. adversarial responses
bad_cases = [
    ("malformed-json", "not-a-dict"),
    ("missing-fields", {"model": jev.REVISION}),
    ("wrong-types", {"model": jev.REVISION,
                     "answers": {"enter": {"type": "noul", "noul": "high"}}}),
    ("answers-keys", None),  # filled below
    ("wrong-revision", dict(good_resp(), model="typesafe/jev-9.99")),
    ("noul-range", None),
]
r = json.loads(json.dumps(good_resp()))
r["answers"]["enter"]["noul"] = 1.5
bad_cases[5] = ("noul-range", r)
r = json.loads(json.dumps(good_resp()))
r["answers"]["mystery"] = {"type": "noul", "noul": 0.5}
bad_cases[3] = ("answers-keys", r)
for name, resp in bad_cases:
    a, why = jev.validate_response(resp)
    check(name, a is None and isinstance(why, str))

# 7. tampered artifact: altered answers / state hash fail verify
row, art = jev.decide(state(symbol="Y"), now=3000.0, key="k",
                      post_fn=mkpost(good_resp()))
art2 = json.loads(json.dumps(art))
art2["payload"]["answers"]["enter"]["noul"] = 0.01
check("altered-response-fails", not jev.verify_answerset(art2))
art3 = json.loads(json.dumps(art))
art3["payload"]["state_hash"] = "0" * 64
check("altered-statehash-fails", not jev.verify_answerset(art3))
art4 = json.loads(json.dumps(art))
art4["signature"] = "00" * 64
check("tampered-sig-fails", not jev.verify_answerset(art4))

# 8. replay: zero network, identical input
p = os.path.join(TMP, "art.json")
json.dump(art, open(p, "w"))
def boom(body, key):
    raise AssertionError("replay must not call provider")
out = jev.replay(p)
check("replay-answers", out["action"] == "ANSWER"
      and out["answers"]["enter"]["noul"] == 0.9 and out["replayed"] is True)
jev_post_orig = jev.post
jev.post = boom
try:
    out = jev.replay(p)
    check("replay-zero-network", out["action"] == "ANSWER")
finally:
    jev.post = jev_post_orig
seed_x, pub_x = jev.keypair()
foreign = dict(art["payload"])
foreign["revision"] = "typesafe/jev-9.99"
msg_x = jev.canon(foreign).encode()
bad_art = {"payload": foreign}
bad_art["response_hash"] = jev.sha256_hex(jev.canon(foreign))
bad_art["signature"] = jev.ed_sign(seed_x, msg_x).hex()
bad_art["pubkey"] = pub_x.hex()
pb = os.path.join(TMP, "bad.json")
json.dump(bad_art, open(pb, "w"))
check("replay-wrong-revision-hold",
      jev.replay(pb)["reason"] == "wrong-revision")

# 9. cost ceiling: pre-exhausted day blocks without calling
day = jev.datetime.now(jev.timezone.utc).strftime("%Y-%m-%d")
jev.SPEND_DIR = os.path.join(TMP, "spend2")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
json.dump({"usd": 0.0, "calls": 5000, "prompt_tokens": 0,
           "completion_tokens": 0},
          open(os.path.join(jev.SPEND_DIR, day + ".json"), "w"))
calls9 = []
row, _ = jev.decide(state(symbol="Z"), now=4000.0, key="k",
                    post_fn=mkpost(good_resp(), calls=calls9))
check("call-ceiling-blocks",
      row["reason"] == "spend-call-ceiling" and calls9 == [])
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10. authority: max conviction + execution family pass through untouched;
#     adapter emits no budget/risk verdicts of its own
resp = good_resp()
resp["answers"]["conviction"]["score"] = "max"
resp["answers"]["edge_family"]["choice"] = "execution"
row, _ = jev.decide(state(symbol="W"), now=4100.0, key="k",
                    post_fn=mkpost(resp))
check("adapter-passthrough-only",
      row["action"] == "ANSWER"
      and row["answers"]["conviction"]["score"] == "max"
      and "2xR" not in json.dumps(row) and "budget" not in json.dumps(row))

# 11b. finite noul: bool/NaN/Inf rejected
import math as _math
for bad_v, name in [(True, "enter-true"), (False, "enter-false"),
                    (float("nan"), "enter-nan"), (float("inf"), "enter-inf")]:
    r = json.loads(json.dumps(good_resp()))
    r["answers"]["enter"]["noul"] = bad_v
    a, why = jev.validate_response(r)
    check(name, a is None)
for bad_v, name in [(True, "latent-true"), (float("nan"), "latent-nan")]:
    r = json.loads(json.dumps(good_resp()))
    r["answers"]["latent_risk"]["noul"] = bad_v
    a, why = jev.validate_response(r)
    check(name, a is None)

# 11c. provider identity enforced
r = json.loads(json.dumps(good_resp()))
r["provider"] = "SomeoneElse"
a, why = jev.validate_response(r)
check("wrong-provider", a is None and why == "wrong-provider")

# 11d. artifact schema: self-describing for C++
row, art = jev.decide(state(symbol="Q"), now=4300.0, key="k",
                      post_fn=mkpost(good_resp()))
pl = art["payload"]
check("artifact-schema",
      set(pl) == {"schema_version", "question_set_version", "model",
                  "revision", "provider", "symbol", "snapshot_epoch",
                  "state_hash", "decision_key", "created_at", "expires_at",
                  "answers"}
      and pl["symbol"] == "Q" and pl["expires_at"] > 4300.0)

# 11e. state binding explicit
check("bind-check-true", jev.bind_check(art, state(symbol="Q")) is True)
check("bind-check-changed-state",
      jev.bind_check(art, state(symbol="Q", snapshot_epoch=99)) is False)
check("bind-check-wrong-symbol",
      jev.bind_check(art, state(symbol="OTHER")) is False)

# 11f. failed attempts carry explicit unknown cost
row, _ = jev.decide(state(symbol="QF"), now=4400.0, key="k",
                    post_fn=mkpost(err="provider-http-500"))
check("unknown-cost-tagged",
      row["action"] == "HOLD" and row["cost"]["usd"] == "unknown"
      and row["cost"]["category"] == "decision")

# 11g. stage 30d USD cap governs (doc 10 units)
jev.SPEND_DIR = os.path.join(TMP, "spend3")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
json.dump({"usd": 150.0, "calls": 5, "prompt_tokens": 0,
           "completion_tokens": 0},
          open(os.path.join(jev.SPEND_DIR, day + ".json"), "w"))
calls_g = []
row, _ = jev.decide(state(symbol="QG"), now=4500.0, key="k",
                    post_fn=mkpost(good_resp(), calls=calls_g))
check("stage-cap-blocks",
      row["reason"] == "spend-stage-cap" and calls_g == [])
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10b. every provider attempt counts, even failures
jev.SPEND_DIR = os.path.join(TMP, "spend4")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
calls_f = []
row, _ = jev.decide(state(symbol="F"), now=4600.0, key="k",
                    post_fn=mkpost(err="provider-timeout", calls=calls_f))
check("attempts-counted",
      row["action"] == "HOLD" and len(calls_f) == 2
      and json.load(open(os.path.join(
          jev.SPEND_DIR,
          __import__("datetime").datetime.now(
              __import__("datetime").timezone.utc).strftime("%Y-%m-%d")
          + ".json")))["calls"] == 2)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10c. rolling 30d ignores stale files
jev.SPEND_DIR = os.path.join(TMP, "spend5")
os.makedirs(jev.SPEND_DIR, exist_ok=True)
old_day = (__import__("datetime").datetime.now(
    __import__("datetime").timezone.utc)
    - __import__("datetime").timedelta(days=40)).strftime("%Y-%m-%d")
json.dump({"usd": 999.0, "calls": 1},
          open(os.path.join(jev.SPEND_DIR, old_day + ".json"), "w"))
check("rolling-window-true", jev.spend_30d() == 0.0)
jev.SPEND_DIR = os.path.join(TMP, "spend")

# 10d. unknown stage fails closed before any provider call
calls_s = []
bad_st = state(symbol="S")
bad_st["stage"] = "G9_MOON"
row, _ = jev.decide(bad_st, now=4700.0, key="k",
                    post_fn=mkpost(good_resp(), calls=calls_s))
check("invalid-stage",
      row["reason"] == "invalid-stage" and calls_s == [])

# 11. bad state input holds deterministically
row, _ = jev.decide({"symbol": "X"}, now=4200.0, key="k",
                    post_fn=mkpost(good_resp()))
check("bad-state-hold", row["action"] == "HOLD")
row, _ = jev.decide("garbage", now=4200.0, key="k",
                    post_fn=mkpost(good_resp()))
check("nonobject-state-hold", row["action"] == "HOLD")

print("ALL JEV CHECKS PASS")
